#!/bin/bash
if ! grep -q "bat" /home/$1/.bash_aliases; then
    VERSION=$(curl -s https://api.github.com/repos/sharkdp/bat/releases/latest | grep '"tag_name"' | cut -d '"' -f 4)
    VERSION_CLEAN=$(echo "$VERSION" | sed 's/^v//')
    curl -LO "https://github.com/sharkdp/bat/releases/download/${VERSION}/bat_${VERSION_CLEAN}_amd64.deb"
    sudo dpkg -i bat_${VERSION_CLEAN}_amd64.deb
    echo "alias cat='bat'" >> /home/$1/.bash_aliases
    echo "alias cat='bat'" >> ~/.config/fish/config.fish
    rm bat_${VERSION_CLEAN}_amd64.deb

else
  echo -e "${GREEN}✓ ${BLUE}Bat already installed.${NC}"
fi

