- name: Debug everything
  run: |
    echo "Environment variables:"
    echo "FTP_SERVER: $FTP_SERVER"
    echo "REMOTE_PATH: $REMOTE_PATH"
    echo "Secrets (should show ****):"
    echo "FTP_USERNAME: ${{ secrets.FTP_USERNAME }}"
    echo "FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}"
