# .github/workflows/deploy.yml
name: Auto Deploy to Website

# Quan executar
on:
  push:
    branches: [ main ]
    paths:
      - 'install.sh'

# Variables globals
env:
  FTP_SERVER: ftp.doomans.com
  REMOTE_PATH: /web

# Tasques
jobs:  
    # 4. Deploy via FTP
    - name: Deploy to FTP
      run: |
        lftp -c "
        set ssl:verify-certificate no
        open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} $FTP_SERVER
        lcd $GITHUB_WORKSPACE
        cd $REMOTE_PATH
        put install.sh
        bye
        "
    
    # 5. Notificar èxit
    - name: Notification
      run: |
        echo "✅ Deploy completat!"
        echo "Fitxers actualitzats a https://doomans.com/scripts/"

