# .github/workflows/deploy.yml
name: Auto Deploy to Website

on:
  push:
    paths:
      - 'install.sh'  # només quan canviï aquest fitxer
    branches: [ main ]
  workflow_dispatch: 

env:
  FTP_SERVER: ftp.doomans.com
  REMOTE_PATH: /web

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy to web  # ← AIXÒ és la clau!
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp
    
    - name: Test FTP connection
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        echo "Testing FTP connection..."
        echo "Username: $FTP_USERNAME (length: ${#FTP_USERNAME})"
        
        lftp -c "
        set ssl:verify-certificate no
        set ftp:ssl-allow no
        open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER
        ls
        pwd
        bye
        "
    
    - name: Deploy file
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "
        set ssl:verify-certificate no
        set ftp:ssl-allow no
        open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER
        cd $REMOTE_PATH
        put install.sh
        ls -la
        bye
        "
