# .github/workflows/deploy.yml
name: Auto Deploy to Website

# Quan executar
on:
  push:
    branches: [ main ]
    paths:
      - 'install.sh'
  workflow_dispatch: 

# Variables globals
env:
  FTP_SERVER: ftp.doomans.com
  REMOTE_PATH: /web

# Tasques
jobs:
  deploy:  # ← FALTAVA: nom del job
    runs-on: ubuntu-latest  # ← FALTAVA: on executar
    
    steps:  # ← FALTAVA: declaració de steps
    # Primer cal descarregar el codi
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Instal·lar lftp
    - name: Install lftp
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp
    
    # Deploy via FTP
    - name: Deploy to FTP
      run: |
        lftp -c "
        set ssl:verify-certificate no
        open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} $FTP_SERVER
        lcd $GITHUB_WORKSPACE
        cd $REMOTE_PATH
        put install.sh
        bye
        "
    
    # Notificar èxit
    - name: Notification
      run: |
        echo "✅ Deploy completat!"
        echo "Fitxers actualitzats a https://doomans.com/scripts/"
